version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: HouseholdProject
      MYSQL_USER: yuki
      MYSQL_PASSWORD: zoids036
      MYSQL_ROOT_HOST: "%"
      BIND-ADDRESS: 0.0.0.0
      TZ: "Asia/Tokyo"
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    networks:
      - household
    volumes:
      - mysql_folder:/var/lib/mysql

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - household
    links:
      - db
    tty: true

  frontend:
    build:
      context: ./frontend
      args:
        API_URL: "http://kakeibo.tk:8000"
    volumes:
      - build_folder:/frontend/build
    tty: true

  nginx:
    build:
      context: ./webserver
    ports:
      - 443:443
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
      - "/srv/letsencrypt:/etc/letsencrypt"
    depends_on:
      - db
      - backend
      - frontend
    tty: true
volumes:
  build_folder:
  mysql_folder:
networks:
  household:
    external: true
