# Generated by Django 3.1.3 on 2021-04-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountBookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='User_date',
            new_name='account_date',
        ),
        migrations.RenameField(
            model_name='spending',
            old_name='User_date',
            new_name='cccount_date',
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.CharField(max_length=30, unique=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='user',
            field=models.CharField(max_length=30, unique=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='incomesubcategory',
            name='user',
            field=models.CharField(max_length=30, unique=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='user',
            field=models.CharField(max_length=30, unique=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='user',
            field=models.CharField(max_length=30, unique=True, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='spendingsubcategory',
            name='user',
            field=models.CharField(max_length=30, unique=True, verbose_name='ユーザーID'),
        ),
    ]
