# Generated by Django 3.1.3 on 2021-04-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountBookapp', '0003_auto_20210421_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spending',
            old_name='cccount_date',
            new_name='account_date',
        ),
    ]
