# Generated by Django 3.1.3 on 2021-04-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountBookapp', '0005_auto_20210422_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='incomesubcategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='サブカテゴリ名'),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='spendingsubcategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='サブカテゴリ名'),
        ),
    ]
