# Generated by Django 3.1.3 on 2021-04-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountBookapp', '0006_auto_20210422_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='AccountBookapp.incomesubcategory', verbose_name='サブカテゴリ'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='AccountBookapp.spendingsubcategory', verbose_name='サブカテゴリ'),
        ),
    ]
